name: SSH Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          mkdir -p ~/.ssh/
          echo "$MOTARC_PRIVATE_KEY" > ~/.ssh/motarc_private
          sudo chmod 600 ~/.ssh/motarc_private
          eval "$(ssh-agent -s)" && ssh-add ~/.ssh/motarc_private
          ssh -tt laravel@157.26.64.211 -p30822
          cd project/motarc
          sudo git pull
          exit
        shell: bash
        env:
          MOTARC_PRIVATE_KEY: ${{secrets.MOTARC_SERVER_TOKEN}}
