name: SSH Deployment
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.MOTARC_SERVER}}
          key: ${{secrets.MOTARC_SERVER_TOKEN}}
          port: ${{secrets.MOTARC_SERVER_PORT}}
          username: ${{secrets.MOTARC_SERVER_USER}}
          script: |
            cd project/motarc
            echo pulling repos...
            sudo git restore .
            sudo git pull --ff-only
            cd ..
            echo running deployment script...
            sudo ./artisan.sh
