name: SSH Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_motarc_rsa
          sudo chmod 600 ~/.ssh/id_motarc_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          eval "$(ssh-agent -s)" && ssh-add.exe ~/.ssh/id_motarc_rsa
          ssh -vvv -tt ${{secrets.MOTARC_SERVER_USER}}@${{secrets.MOTARC_SERVER}} -p${{secrets.MOTARC_SERVER_PORT}}
          cd project/motarc
          echo pulling repos...
          sudo git checkout main
          sudo git pull
          exit
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.MOTARC_SERVER_TOKEN}}
          SSH_KNOWN_HOSTS: ${{secrets.MOTARC_KNOWN_HOSTS}}
